[package]
description = "Platz.io SDK"
edition = "2021"
license-file = "LICENSE"
name = "platz-sdk"
repository = "https://github.com/platzio/sdk-rs"
version = "0.4.2"

[features]
default = ["uuid_08"]
uuid_08 = ["dep:uuid08"]
uuid_1 = ["dep:uuid1"]

[dependencies]
anyhow = "1.0.56"
async-std = "1.11.0"
base64 = "0.13.0"
chrono = {version = "0.4.19", features = ["serde"]}
kv-derive = "1.0.1"
lazy_static = "1.4.0"
reqwest = {version = "0.11.4", default-features = false, features = ["rustls-tls", "json", "gzip", "brotli", "deflate"]}
rust_decimal = "1.17.0"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
strum = {version = "0", features = ["derive"]}
thiserror = "1.0.30"
tracing = "0.1.35"
url = {version = "2.2.2", features = ["serde"]}
uuid08 = {optional = true, package = "uuid", version = "0.8.2", features = ["serde"]}
uuid1 = {optional = true, package = "uuid", version = "1", features = ["serde"]}
